### ISSUE TITLE
Series episode descriptions overflowing

### ISSUE THREAD

**Issue by DesertCookie** [danieladov/jellyfin-plugin-skin-manager#26]
Descriptions of series episodes overflow and become unreadable. This is especially breaking in the Android app, though I wasn't able to get a screenshot at the time. The main problem there was the black background with dark gray text color.

![image](https://user-images.githubusercontent.com/17095983/112859982-b11dd480-90b3-11eb-9ddb-32f028966245.PNG)

**Comment by danieladov** [comment]
Hi, what skin are you using?

**Comment by DesertCookie** [comment]
That'd be JellySkin.

Sorry, I came here from the GitHub posting and wasn't aware this was the plugin repo instead of only the skin repo.

**Comment by danieladov** [comment]
Yeah, you should create the issue here https://github.com/prayag17/JellySkin/issues , the plugin just applies the skin.
