### ISSUE TITLE
Can't uninstall plugin manager 1.5.0.0

### ISSUE THREAD

**Issue by NovaMoon** [danieladov/jellyfin-plugin-skin-manager#35]
Like the title says, i can't remove the plugin from my docker instance. 

nothing is written in the logs, it just simply loads and never finishes.

i can remove any other plugin just fine.

**Comment by Techno-Disaster** [comment]
How was this fixed? 🤔

**Comment by IAmV0id** [comment]
Same problem, please provide the fix if you found one.

**Comment by ChishFoxcat** [comment]
I have the same problem. I checked the console and both disabling and uninstalling returned a 404 error.

![image](https://github.com/danieladov/jellyfin-plugin-skin-manager/assets/76027184/f0048909-fd3c-4598-89c8-4f7e3127f805)
