### ISSUE TITLE
Well, this borked my client

### ISSUE THREAD

**Issue by LoganRTW** [danieladov/jellyfin-plugin-skin-manager#42]
I installed this on through the jellyfin windows client and just clicked on a skin and hit "set" to see how it looked. It was far too bubbly, so I went back into the plugin and clicked it again to open it back up... but was greeted with a blank page and a drop menu that was not clickable. I tried to "uninstall" the plugin... and it refuses to. It just spins for several minutes.. I logged out and in, and now I can't log into Jellyfin. I'm kinda at a loss. Is there anything I can share to help work on this? Is it possible to change back to the default theme by editing an xml file? I'm a bit of a noob and really regretting things right now.

**Comment by danieladov** [comment]
If you get a blank page, try to refresh it

**Comment by LoganRTW** [comment]
I was able to fix it by directly messing with files on the server.. finally got the old theme back
