### ISSUE TITLE
change request for JellyFlix theme playlist display

### ISSUE THREAD

**Issue by mattheweigand** [danieladov/jellyfin-plugin-skin-manager#48]
In the JellyFlix theme, in default.css line 1907, it includes this code: 

```
#itemDetailPage .vertical-list {
  display: grid;
```

This makes playlists display in a grid, filling up a horizontal line before going to the next row. This makes reading and arranging playlist orders pretty much impossible. I would like to request that "display: grid" be deleted so that the playlists can be arranged one item per line. This would allow dragging and dropping playlist items using the included listViewDragHandle.,

**Comment by danieladov** [comment]
Hi, you should report this to the theme repo https://github.com/prayag17/JellyFlix
In the meantime, you can fix it by adding
```

#itemDetailPage .vertical-list {
display:flex;
}
```
to the custom CSS settings under general
