### ISSUE TITLE
Can't change skin

### ISSUE THREAD

**Issue by Big-Papas** [danieladov/jellyfin-plugin-skin-manager#49]
![image](https://user-images.githubusercontent.com/20642344/189905197-ac28dc54-9057-4e8b-a67a-3fd5cee19d9e.png)

As in the image, i changed the skin to ultrachromic (i'm not sure though), and then this happened. When i click the bar to choose an other skin, it doesn't show anything. Tried disabling/re-enabling the plugin and i couldn't because the loading circle was infinitely looping around. I removed it manually from the program data folder and then re installed it (used the official repo mentioned in the announcement of v2.0 reddit) and it is still doing it

**Comment by danieladov** [comment]
Try refreshing the page

**Comment by Big-Papas** [comment]
ok. that did the trick
