### ISSUE TITLE
CSS and Version always show Default

### ISSUE THREAD

**Issue by leaderdog** [danieladov/jellyfin-plugin-skin-manager#5]
Just a small bug.

Whenever I switch to a different skin to check them out both CSS and Version show Default.

So I never know exactly which skin I'm on.

Would be handy if they displayed  which skin you are on and which version you chose.  Some of us have bad memories. :)

This could be a Firefox issue maybe?

Great plugin.  Thanks!

**Comment by danieladov** [comment]
Hi, currently the plugin is not saving which option did you choose. Maybe in the next version could be possible to implement it but it might be a little bit tricky. I will try!

Thanks for the suggestion!

**Comment by danieladov** [comment]
Fixed in last versions
