### ISSUE TITLE
Almost all skins has no image baner as background

### ISSUE THREAD

**Issue by Arturitu12** [danieladov/jellyfin-plugin-skin-manager#50]
Hi, I have an issue that almost all themes except Jellyflix (and default of course) don't use wallpaper/banner images as background of movie page. As I said on these 2 skins it shows but on others theres default color or black background. I already tried on multiple browsers and there's same thing going. Can you help me?

**Comment by danieladov** [comment]
Hi, you should report this to the themes repos
